services:
  frontend:
    build:
      context: ./frontend/Conversey/
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - CI=true
      - VITE_API_BASE_URL=http://35.210.221.59:5231/api
    restart: always

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "5231:5000"
    # GEEN volumes hier, we vertrouwen op de Docker build
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Repository__Type=Postgres
      - ASPNETCORE_URLS=http://+:5000
    restart: always
