services:
    frontend:
      build: 
          context: ./frontend/Conversey/
          dockerfile: Dockerfile
      ports:
          - "5173:5173"
      volumes:
          - ./frontend/Conversey:/app
          - /app/node_modules
      environment:
        #Enables hot reloading
          - CHOKIDAR_USEPOLLING=true
          - CI=true
      command: sh -c "pnpm install && pnpm run dev --host"
