@REST_HostAddress = http://localhost:5001

GET {{REST_HostAddress}}/api/ai/
Accept: application/json
###

### Send POST request with json body
POST {{REST_HostAddress}}/api/ai/submit-idea
Content-Type: application/json

{
  "Content": "Ik ga jouw moeder neuken",
  "ForceSubmit": false
}
###