@REST_HostAddress = http://localhost:5000

GET {{REST_HostAddress}}/api/workspaces/
Accept: application/json

### Send POST request with json body
POST {{REST_HostAddress}}/api/ai/submit-idea
Content-Type: application/json

{
  "Content": "Ik ga jouw moeder neuken",
  "ForceSubmit": false
}
###

POST {{REST_HostAddress}}/api/ideas/
Content-Type: application/json

{
  "Content": "Test Idea",
  "ProjectId": 1 
}
###
